volumes:
  learn_nextjs_data: { }

services:
  postgres:
    image: postgres:16
    container_name: learn_nextjs
    volumes: 
      - learn_nextjs_data:/var/lib/postgresql/data
    env_file: .env
    ports:
     - "5432:5432"

